-- Real invoice data sourced from invoice_and_do/*.xlsx files.
-- Runs after 05_real_purchase_orders.sql.
--
-- Strategy:
--   1. Ensure each real PO has an invoice row (call fn_create_invoice for
--      POs whose status never reached DELIVERED in seed 04).
--   2. Override invoice_date / due_date / status with values pulled from the
--      .xlsx files.
--   3. Invoice numbers, line items, dpp, ppn stay as the auto-generated values
--      because items mirror purchase_order_items (snapshot rebuilt by 05).
--
-- Status heuristic: invoice with due_date <= 2026-05-09 -> 'paid', else 'sent'.
-- Coverage: 56/57 POs matched to invoice files. qid 549 (Q-2640061) has a real
-- PO but no invoice file yet, so it stays accepted with a PO and no invoice.

BEGIN;

-- 1. Create invoice rows for real-PO quotations that didn't auto-gen one.
DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN
    SELECT po.id, COALESCE(po.updated_by, po.created_by) AS user_id
      FROM purchase_orders po
      JOIN (VALUES
        (478::bigint),
        (481::bigint),
        (486::bigint),
        (488::bigint),
        (489::bigint),
        (490::bigint),
        (491::bigint),
        (492::bigint),
        (498::bigint),
        (500::bigint),
        (506::bigint),
        (509::bigint),
        (512::bigint),
        (519::bigint),
        (520::bigint),
        (522::bigint),
        (523::bigint),
        (524::bigint),
        (526::bigint),
        (528::bigint),
        (530::bigint),
        (537::bigint),
        (542::bigint),
        (543::bigint),
        (544::bigint),
        (548::bigint),
        (552::bigint),
        (555::bigint),
        (556::bigint),
        (557::bigint),
        (565::bigint),
        (568::bigint),
        (571::bigint),
        (573::bigint),
        (575::bigint),
        (576::bigint),
        (587::bigint),
        (589::bigint),
        (593::bigint),
        (604::bigint),
        (605::bigint),
        (611::bigint),
        (614::bigint),
        (619::bigint),
        (624::bigint),
        (640::bigint),
        (641::bigint),
        (643::bigint),
        (645::bigint),
        (646::bigint),
        (647::bigint),
        (649::bigint),
        (654::bigint),
        (660::bigint),
        (668::bigint),
        (669::bigint)
      ) AS rp(quotation_id) ON rp.quotation_id = po.quotation_id
      WHERE NOT EXISTS (SELECT 1 FROM invoices i WHERE i.po_id = po.id)
  LOOP
    PERFORM fn_create_invoice(r.id, r.user_id);
  END LOOP;
END $$;

-- 2. Override invoice header (date / due / status). Invoice number stays as
--    auto-generated by fn_next_doc_no, items are mirrored from PO.
UPDATE invoices i
   SET invoice_date = v.invoice_date,
       due_date     = v.due_date,
       status       = v.status,
       updated_by   = i.created_by
  FROM (VALUES
    (544::bigint, '2026-02-10'::date, '2026-03-12'::date, 'paid'),  -- 025_2_2026 - Siemens UVR - Karunia Aman Sentosa.xl
    (526::bigint, '2026-01-26'::date, '2026-02-25'::date, 'paid'),  -- 017_I_2026 - Karunia Aman Sentosa.xlsx
    (556::bigint, '2026-03-11'::date, '2026-04-10'::date, 'paid'),  -- 032_2_2026 - Selenoid Valve - Karunia Aman Sentosa
    (605::bigint, '2026-03-17'::date, '2026-04-16'::date, 'paid'),  -- 042_3_2026 - Power Supply Diamond GZV4000 - Karuni
    (557::bigint, '2026-02-25'::date, '2026-03-27'::date, 'paid'),  -- 033_2_2026 - Module Sices GC250 - Karunia Aman Sen
    (593::bigint, '2026-03-04'::date, '2026-04-03'::date, 'paid'),  -- 037_3_2026 - Nozzle Cleaner Gun - Karunia Aman Sen
    (646::bigint, '2026-05-07'::date, '2026-06-06'::date, 'sent'),  -- 056_5_2026 - Vbelt TB Aman 06 - Karunia Aman Sento
    (668::bigint, '2026-01-26'::date, '2026-02-25'::date, 'paid'),  -- 016_I_2026 - Karunia Aman Sentosa.xlsx
    (669::bigint, '2026-02-10'::date, '2026-03-12'::date, 'paid'),  -- 025_2_2026 - ComAp Inteli Nano Module - Karunia Am
    (611::bigint, '2026-04-13'::date, '2026-05-13'::date, 'sent'),  -- 046_4_2026 - Breaker MCCB - NS 100 N - Karunia Ama
    (614::bigint, '2026-04-10'::date, '2026-05-10'::date, 'sent'),  -- 043_4_2026 - Racor 2040 2010 - Karunia Aman Selalu
    (640::bigint, '2026-04-20'::date, '2026-05-20'::date, 'sent'),  -- 051_4_2026 - Magnafluk - Karunia Aman Selalu.xlsx
    (654::bigint, '2026-05-02'::date, '2026-06-01'::date, 'sent'),  -- 054_5_2026 - Vbelt AE 3911588 - Karunia Aman Selal
    (486::bigint, '2026-02-10'::date, '2026-03-12'::date, 'paid'),  -- 024_II_2026 - Karunia Aman Selalu.xlsx
    (478::bigint, '2026-01-20'::date, '2026-02-19'::date, 'paid'),  -- 015_I_2026 - Karunia Aman Selalu.xlsx
    (481::bigint, '2026-03-04'::date, '2026-04-03'::date, 'paid'),  -- 036_2_2026 - Roller Stator - Karunia Aman Selalu.x
    (571::bigint, '2026-03-12'::date, '2026-04-11'::date, 'paid'),  -- 041_3_2026 - Relay Schneider - Karunia Aman Selalu
    (645::bigint, '2026-04-10'::date, '2026-05-10'::date, 'sent'),  -- 045_4_2026 - Vbelt Ribbed C3911588 - Karunia Aman
    (619::bigint, '2026-04-13'::date, '2026-05-13'::date, 'sent'),  -- 047_4_2026 - Dial Bore - Karunia Aman Selalu.xlsx
    (555::bigint, '2026-02-11'::date, '2026-02-26'::date, 'paid'),  -- 035_2_2026 - Kompresor United - Yuxin Satu - IMC S
    (643::bigint, '2026-04-22'::date, '2026-05-22'::date, 'sent'),  -- 052_4_2026 Kompresor PUMA (used) - Yuxin Shipping
    (552::bigint, '2026-03-05'::date, '2026-04-04'::date, 'paid'),  -- 038_3_2026 - O-RING NBR NOK VR32A - Niterra.xlsx
    (589::bigint, '2026-05-05'::date, '2026-06-04'::date, 'sent'),  -- 055_5_2026 - SEAL KIT AIR CYLINDER NEW - Niterra.x
    (604::bigint, '2026-04-08'::date, '2026-05-08'::date, 'paid'),  -- 044_4_2026 - Seal Kit Oil Pump Tekawe - Niterra.xl
    (587::bigint, '2026-04-20'::date, '2026-05-20'::date, 'sent'),  -- 050_4_2026 - RING Kotak - Niterra.xlsx
    (490::bigint, '2026-01-19'::date, '2026-02-18'::date, 'paid'),  -- 006_1_2026 - PO-TCP_I_2026-00026 - KPC Floating As
    (489::bigint, '2026-01-19'::date, '2026-02-18'::date, 'paid'),  -- 005_1_2026 - PO TCP-2512-00540 - FC PIONEER Sangat
    (488::bigint, '2026-01-08'::date, '2026-02-08'::date, 'paid'),  -- 10611_1_2026 - Pengiriman ke Sangatta - PT Transco
    (530::bigint, '2026-02-03'::date, '2026-02-18'::date, 'paid'),  -- 026_2_2026 - PO-SML_II_2026-00004 - Gland Packing
    (576::bigint, '2026-03-04'::date, '2026-04-03'::date, 'paid'),  -- 038_3_2026 - Sentra Makmur Lines.xlsx
    (660::bigint, '2026-05-07'::date, '2026-06-06'::date, 'sent'),  -- 057_5_2026 - Flow meter - Kasen Maritim Logistik.x
    (624::bigint, '2026-04-22'::date, '2026-05-22'::date, 'sent'),  -- 049_4_2026 - Infrared Night Vision Binocular - Dew
    (565::bigint, '2026-02-24'::date, '2026-03-26'::date, 'paid'),  -- 027_2_2026 - Cardboard - Dewi Saraswati - Pelita G
    (649::bigint, '2026-05-07'::date, '2026-06-06'::date, 'sent'),  -- 053_4_2026 - Obat  - Dewi Shinta Manggala - Pelita
    (647::bigint, '2026-04-22'::date, '2026-05-22'::date, 'sent'),  -- 10616_4_2026 - Pengiriman dan boat CIlegon - Pelit
    (641::bigint, '2026-04-22'::date, '2026-05-22'::date, 'sent'),  -- 048_4_2026 - Gangway and Pilot Ladder  - Dewi Shin
    (568::bigint, '2026-02-24'::date, '2026-03-26'::date, 'paid'),  -- 031_2_2026 - Tape Hatch Cover - Dewi Shinta Mangga
    (537::bigint, '2026-01-27'::date, '2026-02-20'::date, 'paid'),  -- 023B_2_2026 - Cover Lampu Custom partial 2 - Pelit
    (548::bigint, '2026-02-05'::date, '2026-03-07'::date, 'paid'),  -- 022_2_2026 - HT ENTEL DX544 VHF INTRINSICALLY SAFE
    (573::bigint, '2026-02-24'::date, '2026-03-26'::date, 'paid'),  -- 030_2_2026 - Vacuum Pump Suction  - Pelita Almeira
    (492::bigint, '2026-01-19'::date, '2026-02-18'::date, 'paid'),  -- 001_I_2026 - Printer - Daidan Pertiwi - Pelita Glo
    (575::bigint, '2026-02-24'::date, '2026-03-26'::date, 'paid'),  -- 029_2_2026 - Freon 407 - Pelita Almeira Pertiwi -
    (528::bigint, '2026-02-03'::date, '2026-03-05'::date, 'paid'),  -- 018_1_2026 - ANGLE VALVE 10K 125 SDNR - Pelita Alm
    (523::bigint, '2026-01-27'::date, '2026-02-26'::date, 'paid'),  -- 014_1_2026 - BUTTERFLY VALVE WAFER TYPE DN 150 - D
    (509::bigint, '2026-01-19'::date, '2026-02-18'::date, 'paid'),  -- 009_1_2026 - Butterfly Valve - Daidan Pertiwi - Pe
    (512::bigint, '2026-01-19'::date, '2026-02-18'::date, 'paid'),  -- 007_1_2026 - spare roller, demolation dll - Daidan
    (543::bigint, '2026-02-04'::date, '2026-03-06'::date, 'paid'),  -- 019_1_2026 - Check Valves DIN Bronze PN10 - Pelita
    (491::bigint, '2026-01-19'::date, '2026-02-18'::date, 'paid'),  -- 002_1_2026 - Floodlight 100w - Daidan Pertiwi - Pe
    (519::bigint, '2026-01-21'::date, '2026-02-20'::date, 'paid'),  -- 011_1_2026 - Impeller - Daidan Pertiwi - Pelita Gl
    (524::bigint, '2026-01-27'::date, '2026-02-26'::date, 'paid'),  -- 013_1_2026 - Angle Valve - Daidan Pertiwi - Pelita
    (522::bigint, '2026-01-27'::date, '2026-02-26'::date, 'paid'),  -- 012_1_2026 - Butterfly Valve double flange 5K 200
    (500::bigint, '2026-01-19'::date, '2026-02-18'::date, 'paid'),  -- 004_1_2026 - Cordless Impact Wrench - Daidan Perti
    (506::bigint, '2026-01-19'::date, '2026-02-18'::date, 'paid'),  -- 008_1_2026 - kunci shock, dakron dll  - Daidan Per
    (498::bigint, '2026-01-19'::date, '2026-02-18'::date, 'paid'),  -- 003_1_2026 - Wearpacks - Daidan Pertiwi - Pelita G
    (542::bigint, '2026-02-05'::date, '2026-03-07'::date, 'paid'),  -- 020_2_2026 - Pressure Gauge dll - Pelita Almeira P
    (520::bigint, '2026-01-19'::date, '2026-02-18'::date, 'paid')  -- 010_1_2026 - Marine Cast Iron F-7363 - Daidan Pert
  ) AS v(quotation_id, invoice_date, due_date, status)
  JOIN purchase_orders po ON po.quotation_id = v.quotation_id
 WHERE i.po_id = po.id;

-- 3. Sanity check: every real-PO invoice must have items matching its PO.
--    invoice_items mirrors purchase_order_items via fn_create_invoice +
--    migration 00021. This raises if any mismatch is detected.
DO $$
DECLARE n_mismatch INT;
BEGIN
  SELECT count(*) INTO n_mismatch FROM (
    SELECT po.id AS po_id,
           (SELECT count(*) FROM purchase_order_items WHERE po_id = po.id) AS po_n,
           (SELECT count(*) FROM invoice_items ii JOIN invoices i ON i.id=ii.invoice_id WHERE i.po_id = po.id) AS inv_n
      FROM purchase_orders po
      JOIN (VALUES
        (478::bigint),
        (481::bigint),
        (486::bigint),
        (488::bigint),
        (489::bigint),
        (490::bigint),
        (491::bigint),
        (492::bigint),
        (498::bigint),
        (500::bigint),
        (506::bigint),
        (509::bigint),
        (512::bigint),
        (519::bigint),
        (520::bigint),
        (522::bigint),
        (523::bigint),
        (524::bigint),
        (526::bigint),
        (528::bigint),
        (530::bigint),
        (537::bigint),
        (542::bigint),
        (543::bigint),
        (544::bigint),
        (548::bigint),
        (552::bigint),
        (555::bigint),
        (556::bigint),
        (557::bigint),
        (565::bigint),
        (568::bigint),
        (571::bigint),
        (573::bigint),
        (575::bigint),
        (576::bigint),
        (587::bigint),
        (589::bigint),
        (593::bigint),
        (604::bigint),
        (605::bigint),
        (611::bigint),
        (614::bigint),
        (619::bigint),
        (624::bigint),
        (640::bigint),
        (641::bigint),
        (643::bigint),
        (645::bigint),
        (646::bigint),
        (647::bigint),
        (649::bigint),
        (654::bigint),
        (660::bigint),
        (668::bigint),
        (669::bigint)
      ) AS rp(quotation_id) ON rp.quotation_id = po.quotation_id
  ) t WHERE po_n <> inv_n;
  IF n_mismatch > 0 THEN
    RAISE EXCEPTION 'Invoice item count mismatch on % real-PO invoices', n_mismatch;
  END IF;
END $$;

-- 4. An invoice existing means the goods were delivered. Advance every PO
--    that has an invoice to DELIVERED and stamp its delivery note number,
--    matching fn_change_po_status. Direct UPDATE is the seed-time exception:
--    fn_change_po_status would re-run the invoice draft.
UPDATE purchase_orders po
   SET status               = 'DELIVERED',
       delivery_note_number = COALESCE(
         po.delivery_note_number,
         fn_next_doc_no('DN', po.company_client_id)
       )
 WHERE po.status <> 'DELIVERED'
   AND EXISTS (SELECT 1 FROM invoices i WHERE i.po_id = po.id);

COMMIT;
