-- +goose Up
-- +goose StatementBegin

-- ============================================================
-- 00006 — COUNTRY MASTER
-- ============================================================
-- ISO 3166 country codes + ITU-T E.164 dial codes
-- Used by:
--   * company_client.country_code (FK candidate)
--   * Step1 client add modal (search + auto-fill phone prefix)
-- ============================================================

CREATE TABLE countries (
  code      VARCHAR(3)   PRIMARY KEY,    -- ISO 3166 alpha-3 (some 2-letter for territories)
  name      VARCHAR(100) NOT NULL,
  dial_code VARCHAR(10)  NOT NULL        -- E.164 dial code, "" for stateless
);

-- Index for case-insensitive name search (FE typically searches by name)
CREATE INDEX idx_countries_name_trgm ON countries USING GIN (name gin_trgm_ops);

-- +goose StatementEnd


-- +goose StatementBegin
INSERT INTO countries (code, name, dial_code) VALUES
  ('ABW', 'Aruba', '+297'),
  ('AFG', 'Afghanistan', '+93'),
  ('AGO', 'Angola', '+244'),
  ('AIA', 'Anguilla', '+1'),
  ('ALA', 'Aland Islands', '+358'),
  ('ALB', 'Albania', '+355'),
  ('AND', 'Andorra', '+376'),
  ('ARE', 'United Arab Emirates', '+971'),
  ('ARG', 'Argentina', '+54'),
  ('ARM', 'Armenia', '+374'),
  ('ASM', 'American Samoa', '+1'),
  ('ATA', 'Antarctica', '+672'),
  ('ATF', 'French Southern Territories', '+262'),
  ('ATG', 'Antigua and Barbuda', '+1'),
  ('AUS', 'Australia', '+61'),
  ('AUT', 'Austria', '+43'),
  ('AZE', 'Azerbaijan', '+994'),
  ('BDI', 'Burundi', '+257'),
  ('BEL', 'Belgium', '+32'),
  ('BEN', 'Benin', '+229'),
  ('BES', 'Bonaire, Sint Eustatius and Saba', '+599'),
  ('BFA', 'Burkina Faso', '+226'),
  ('BGD', 'Bangladesh', '+880'),
  ('BGR', 'Bulgaria', '+359'),
  ('BHR', 'Bahrain', '+973'),
  ('BHS', 'Bahamas', '+1'),
  ('BIH', 'Bosnia and Herzegovina', '+387'),
  ('BLM', 'Saint Barthelemy', '+590'),
  ('BLR', 'Belarus', '+375'),
  ('BLZ', 'Belize', '+501'),
  ('BMU', 'Bermuda', '+1'),
  ('BOL', 'Bolivia, Plurinational State of', '+591'),
  ('BRA', 'Brazil', '+55'),
  ('BRB', 'Barbados', '+1'),
  ('BRN', 'Brunei Darussalam', '+673'),
  ('BTN', 'Bhutan', '+975'),
  ('BVT', 'Bouvet Island', '+47'),
  ('BWA', 'Botswana', '+267'),
  ('CAF', 'Central African Republic', '+236'),
  ('CAN', 'Canada', '+1'),
  ('CCK', 'Cocos (Keeling) Islands', '+61'),
  ('CHE', 'Switzerland', '+41'),
  ('CHL', 'Chile', '+56'),
  ('CHN', 'China', '+86'),
  ('CIV', 'Cote d''Ivoire', '+225'),
  ('CMR', 'Cameroon', '+237'),
  ('COD', 'Congo, Democratic Republic of the', '+243'),
  ('COG', 'Congo', '+242'),
  ('COK', 'Cook Islands', '+682'),
  ('COL', 'Colombia', '+57'),
  ('COM', 'Comoros', '+269'),
  ('CPV', 'Cabo Verde', '+238'),
  ('CRI', 'Costa Rica', '+506'),
  ('CUB', 'Cuba', '+53'),
  ('CUW', 'Curacao', '+599'),
  ('CXR', 'Christmas Island', '+61'),
  ('CY',  'Cyprus', '+357'),
  ('CYM', 'Cayman Islands', '+1'),
  ('CZE', 'Czech Republic', '+420'),
  ('DEU', 'Germany', '+49'),
  ('DJI', 'Djibouti', '+253'),
  ('DMA', 'Dominica', '+1'),
  ('DNK', 'Denmark', '+45'),
  ('DOM', 'Dominican Republic', '+1'),
  ('DZA', 'Algeria', '+213'),
  ('ECU', 'Ecuador', '+593'),
  ('EGY', 'Egypt', '+20'),
  ('ERI', 'Eritrea', '+291'),
  ('ESH', 'Western Sahara', '+212'),
  ('ESP', 'Spain', '+34'),
  ('EST', 'Estonia', '+372'),
  ('ETH', 'Ethiopia', '+251'),
  ('FIN', 'Finland', '+358'),
  ('FJ',  'Fiji', '+679'),
  ('FLK', 'Falkland Islands (Malvinas)', '+500'),
  ('FRA', 'France', '+33'),
  ('FRO', 'Faroe Islands', '+298'),
  ('FSM', 'Micronesia, Federated States of', '+691'),
  ('GAB', 'Gabon', '+241'),
  ('GBR', 'United Kingdom', '+44'),
  ('GEO', 'Georgia', '+995'),
  ('GGY', 'Guernsey', '+44'),
  ('GHA', 'Ghana', '+233'),
  ('GIB', 'Gibraltar', '+350'),
  ('GIN', 'Guinea', '+224'),
  ('GLP', 'Guadeloupe', '+590'),
  ('GMB', 'Gambia', '+220'),
  ('GNB', 'Guinea-Bissau', '+245'),
  ('GQ',  'Equatorial Guinea', '+240'),
  ('GRC', 'Greece', '+30'),
  ('GRD', 'Grenada', '+1'),
  ('GRL', 'Greenland', '+299'),
  ('GS',  'South Georgia And The South Sandwich Islands', '+500'),
  ('GTM', 'Guatemala', '+502'),
  ('GUF', 'French Guiana', '+594'),
  ('GUM', 'Guam', '+1'),
  ('GUY', 'Guyana', '+592'),
  ('HKG', 'Hong Kong', '+852'),
  ('HMD', 'Heard Island and McDonald Islands', '+672'),
  ('HND', 'Honduras', '+504'),
  ('HRV', 'Croatia', '+385'),
  ('HTI', 'Haiti', '+509'),
  ('HUN', 'Hungary', '+36'),
  ('IDN', 'Indonesia', '+62'),
  ('IM',  'Isle of Man', '+44'),
  ('IND', 'India', '+91'),
  ('IOT', 'British Indian Ocean Territory', '+246'),
  ('IRL', 'Ireland', '+353'),
  ('IRN', 'Iran, Islamic Republic of', '+98'),
  ('IRQ', 'Iraq', '+964'),
  ('ISL', 'Iceland', '+354'),
  ('ISR', 'Israel', '+972'),
  ('ITA', 'Italy', '+39'),
  ('JAM', 'Jamaica', '+1'),
  ('JE',  'Jersey', '+44'),
  ('JOR', 'Jordan', '+962'),
  ('JPN', 'Japan', '+81'),
  ('KAZ', 'Kazakhstan', '+7'),
  ('KEN', 'Kenya', '+254'),
  ('KGZ', 'Kyrgyzstan', '+996'),
  ('KHM', 'Cambodia', '+855'),
  ('KI',  'Kiribati', '+686'),
  ('KNA', 'Saint Kitts and Nevis', '+1'),
  ('KOR', 'Korea, the Republic of', '+82'),
  ('KR',  'Kosovo', '+383'),
  ('KWT', 'Kuwait', '+965'),
  ('LAO', 'Lao People''s Democratic Republic', '+856'),
  ('LBN', 'Lebanon', '+961'),
  ('LBR', 'Liberia', '+231'),
  ('LBY', 'Libya', '+218'),
  ('LCA', 'Saint Lucia', '+1'),
  ('LIE', 'Liechtenstein', '+423'),
  ('LK',  'Stateless', ''),
  ('LKA', 'Sri Lanka', '+94'),
  ('LSO', 'Lesotho', '+266'),
  ('LTU', 'Lithuania', '+370'),
  ('LUX', 'Luxembourg', '+352'),
  ('LVA', 'Latvia', '+371'),
  ('MAC', 'Macao', '+853'),
  ('MAF', 'Saint Martin (French part)', '+590'),
  ('MAR', 'Morocco', '+212'),
  ('MCO', 'Monaco', '+377'),
  ('MDA', 'Moldova, the Republic of', '+373'),
  ('MDG', 'Madagascar', '+261'),
  ('MDV', 'Maldives', '+960'),
  ('MEX', 'Mexico', '+52'),
  ('MHL', 'Marshall Islands', '+692'),
  ('MK',  'Macedonia, The Former Yugoslav Republic of', '+389'),
  ('MLI', 'Mali', '+223'),
  ('MLT', 'Malta', '+356'),
  ('MM',  'Myanmar', '+95'),
  ('MNE', 'Montenegro', '+382'),
  ('MNG', 'Mongolia', '+976'),
  ('MNP', 'Northern Mariana Islands', '+1'),
  ('MOZ', 'Mozambique', '+258'),
  ('MRT', 'Mauritania', '+222'),
  ('MSR', 'Montserrat', '+1'),
  ('MTQ', 'Martinique', '+596'),
  ('MUS', 'Mauritius', '+230'),
  ('MWI', 'Malawi', '+265'),
  ('MYS', 'Malaysia', '+60'),
  ('NAM', 'Namibia', '+264'),
  ('NCL', 'New Caledonia', '+687'),
  ('NER', 'Niger', '+227'),
  ('NFK', 'Norfolk Island', '+672'),
  ('NGA', 'Nigeria', '+234'),
  ('NIC', 'Nicaragua', '+505'),
  ('NIU', 'Niue', '+683'),
  ('NLD', 'Netherlands', '+31'),
  ('NOR', 'Norway', '+47'),
  ('NPL', 'Nepal', '+977'),
  ('NRU', 'Nauru', '+674'),
  ('NZL', 'New Zealand', '+64'),
  ('OAT', 'Qatar', '+974'),
  ('OMN', 'Oman', '+968'),
  ('PAK', 'Pakistan', '+92'),
  ('PAN', 'Panama', '+507'),
  ('PCN', 'Pitcairn', '+64'),
  ('PER', 'Peru', '+51'),
  ('PHL', 'Philippines', '+63'),
  ('PLW', 'Palau', '+680'),
  ('PNG', 'Papua New Guinea', '+675'),
  ('POL', 'Poland', '+48'),
  ('PRI', 'Puerto Rico', '+1'),
  ('PRK', 'Korea, Democratic People''s Republic of', '+850'),
  ('PRT', 'Portugal', '+351'),
  ('PRY', 'Paraguay', '+595'),
  ('PS',  'Palestine, State of', '+970'),
  ('PYF', 'French Polynesia', '+689'),
  ('REU', 'Reunion', '+262'),
  ('ROU', 'Romania', '+40'),
  ('RUS', 'Russian Federation', '+7'),
  ('RWA', 'Rwanda', '+250'),
  ('SAU', 'Saudi Arabia', '+966'),
  ('SB',  'Solomon Islands', '+677'),
  ('SDN', 'Sudan', '+249'),
  ('SEN', 'Senegal', '+221'),
  ('SGP', 'Singapore', '+65'),
  ('SHN', 'Saint Helena, Ascension and Tristan da Cunha', '+290'),
  ('SJM', 'Svalbard and Jan Mayen', '+47'),
  ('SLE', 'Sierra Leone', '+232'),
  ('SLV', 'El Salvador', '+503'),
  ('SMR', 'San Marino', '+378'),
  ('SOM', 'Somalia', '+252'),
  ('SPM', 'Saint Pierre and Miquelon', '+508'),
  ('SRB', 'Serbia', '+381'),
  ('SSD', 'South Sudan', '+211'),
  ('STP', 'Sao Tome and Principe', '+239'),
  ('SUR', 'Suriname', '+597'),
  ('SVK', 'Slovakia', '+421'),
  ('SVN', 'Slovenia', '+386'),
  ('SWE', 'Sweden', '+46'),
  ('SWZ', 'Swaziland', '+268'),
  ('SXM', 'Sint Maarten (Dutch part)', '+1'),
  ('SYC', 'Seychelles', '+248'),
  ('SYR', 'Syrian Arab Republic', '+963'),
  ('TCA', 'Turks and Caicos Islands', '+1'),
  ('TCD', 'Chad', '+235'),
  ('TGO', 'Togo', '+228'),
  ('THA', 'Thailand', '+66'),
  ('TJK', 'Tajikistan', '+992'),
  ('TKL', 'Tokelau', '+690'),
  ('TKM', 'Turkmenistan', '+993'),
  ('TLS', 'Timor-Leste', '+670'),
  ('TON', 'Tonga', '+676'),
  ('TTO', 'Trinidad and Tobago', '+1'),
  ('TUN', 'Tunisia', '+216'),
  ('TUR', 'Turkey', '+90'),
  ('TUV', 'Tuvalu', '+688'),
  ('TWN', 'Taiwan', '+886'),
  ('TZ',  'Tanzania, United Republic of', '+255'),
  ('UGA', 'Uganda', '+256'),
  ('UKR', 'Ukraine', '+380'),
  ('UMI', 'United States Minor Outlying Islands', '+1'),
  ('URY', 'Uruguay', '+598'),
  ('USA', 'United States of America', '+1'),
  ('UZB', 'Uzbekistan', '+998'),
  ('VAT', 'Holy See (Vatican City State)', '+379'),
  ('VCT', 'Saint Vincent and the Grenadines', '+1'),
  ('VEN', 'Venezuela, Bolivarian Republic of', '+58'),
  ('VGB', 'Virgin Islands, British', '+1'),
  ('VIR', 'Virgin Islands, U.S.', '+1'),
  ('VNM', 'Viet Nam', '+84'),
  ('VUT', 'Vanuatu', '+678'),
  ('WLF', 'Wallis and Futuna', '+681'),
  ('WS',  'Samoa', '+685'),
  ('YEM', 'Yemen', '+967'),
  ('YT',  'Mayotte', '+262'),
  ('ZAF', 'South Africa', '+27'),
  ('ZMB', 'Zambia', '+260'),
  ('ZWE', 'Zimbabwe', '+263');
-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin
DROP INDEX IF EXISTS idx_countries_name_trgm;
DROP TABLE IF EXISTS countries;
-- +goose StatementEnd
