// Gentypes writes web API types.
//
// It reads the allowlisted Go DTOs with coder/guts and writes
// apps/web/src/types/generated.ts. Run it through `make gen-types` from the
// repo root; CI regenerates and fails on any diff.
package main

import (
	"errors"
	"flag"
	"fmt"
	"go/types"
	"os"
	"slices"
	"strings"

	"github.com/coder/guts"
	"github.com/coder/guts/bindings"
	"github.com/coder/guts/bindings/walk"
	"github.com/coder/guts/config"
)

const header = `// Generated by make gen-types.
//
// Source: the Go DTOs allowlisted in apps/api/cmd/gentypes. Do not edit;
// change the Go type and regenerate. Three rules shape the output:
// - A response field tagged omitempty is optional and never null, since Go
//   drops the key instead of sending null.
// - A request (Input) field that Go reads through a pointer is optional,
//   since Go decodes an absent key as nil.
// - Slices and maps are typed non-null; a handler must send them empty,
//   never nil.

`

func main() {
	out := flag.String("out", "", "output file (stdout when empty)")
	flag.Parse()
	src, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, "gentypes:", err)
		os.Exit(1)
	}
	if *out == "" {
		fmt.Print(src)
		return
	}
	if err := os.WriteFile(*out, []byte(src), 0o600); err != nil {
		fmt.Fprintln(os.Stderr, "gentypes:", err)
		os.Exit(1)
	}
}

// goKey identifies one Go type.
type goKey struct{ pkg, name string }

// plan is the resolved allowlist.
type plan struct {
	byGo   map[goKey]entry
	prefix map[string]string // package path to guts prefix
}

func newPlan() (plan, error) {
	p := plan{byGo: map[goKey]entry{}, prefix: map[string]string{}}
	seen := map[string]goKey{}
	for i, pk := range allowlist {
		path := module + "/" + pk.Path
		// A unique prefix keeps guts keys apart; rename drops it.
		p.prefix[path] = fmt.Sprintf("P%d_", i)
		for _, e := range pk.Types {
			k := goKey{path, e.Go}
			if prev, dup := seen[e.TS]; dup {
				return p, fmt.Errorf("ts name %s used by %s.%s and %s.%s", e.TS, prev.pkg, prev.name, k.pkg, k.name)
			}
			seen[e.TS] = k
			p.byGo[k] = e
		}
	}
	return p, nil
}

func generate() (string, error) {
	pl, err := newPlan()
	if err != nil {
		return "", err
	}
	gp, err := guts.NewGolangParser()
	if err != nil {
		return "", err
	}
	gp.IncludeCustomDeclaration(config.StandardMappings())
	gp.IncludeCustomDeclaration(map[string]guts.TypeOverride{
		// Stored JSONB without a server shape.
		"encoding/json.RawMessage": config.OverrideLiteral(bindings.KeywordUnknown),
		// Tri-state text: absent keeps, null or blank clears.
		module + "/internal/shared/httpx.OptionalText": config.OverrideNullable(config.OverrideLiteral(bindings.KeywordString)),
	})
	for _, pk := range allowlist {
		path := module + "/" + pk.Path
		if err := gp.IncludeGenerateWithPrefix(path, pl.prefix[path]); err != nil {
			return "", err
		}
	}
	if err := skipUnlisted(gp, pl); err != nil {
		return "", err
	}

	ts, err := gp.ToTypescript()
	if err != nil {
		return "", err
	}
	keep := map[string]string{} // guts key to ts name
	for k, e := range pl.byGo {
		keep[pl.prefix[k.pkg]+k.name] = e.TS
	}
	var errs []error
	ts.ApplyMutations(
		config.EnumAsTypes,
		config.SimplifyOptional,
		config.NotNullMaps,
		optionalInputs(pl),
		rename(pl, &errs),
		config.InterfaceToType,
		config.ExportTypes,
	)
	if len(errs) > 0 {
		return "", errors.Join(errs...)
	}
	for key := range keep {
		if _, ok := ts.Node(key); !ok {
			return "", fmt.Errorf("allowlisted %s was not generated", key)
		}
	}
	body, err := ts.SerializeInOrder(func(nodes map[string]bindings.Node) []bindings.Node {
		keys := make([]string, 0, len(keep))
		for k := range keep {
			keys = append(keys, k)
		}
		slices.SortFunc(keys, func(a, b string) int { return strings.Compare(keep[a], keep[b]) })
		out := make([]bindings.Node, 0, len(keys))
		for _, k := range keys {
			out = append(out, nodes[k])
		}
		return out
	})
	if err != nil {
		return "", err
	}
	body = strings.TrimPrefix(body, "// Code generated by 'guts'. DO NOT EDIT.\n\n")
	return header + strings.TrimRight(body, "\n") + "\n", nil
}

// skipUnlisted drops non-DTO declarations.
// Handlers, repos and filters never reach the web, and skipping them keeps
// guts from parsing types it cannot express.
func skipUnlisted(gp *guts.GoParser, pl plan) error {
	for path, pkg := range gp.Pkgs {
		if len(pkg.Errors) > 0 {
			return fmt.Errorf("load %s: %v", path, pkg.Errors[0])
		}
		scope := pkg.Types.Scope()
		for _, name := range scope.Names() {
			obj, ok := scope.Lookup(name).(*types.TypeName)
			if !ok || !obj.Exported() {
				continue
			}
			if _, listed := pl.byGo[goKey{path, name}]; listed {
				continue
			}
			if err := gp.ExcludeCustom(obj.Type().String()); err != nil {
				return err
			}
		}
	}
	return nil
}

// optionalInputs relaxes request pointers.
func optionalInputs(pl plan) guts.MutationFunc {
	inputs := map[string]bool{}
	for k, e := range pl.byGo {
		if e.Input {
			inputs[pl.prefix[k.pkg]+k.name] = true
		}
	}
	return func(ts *guts.Typescript) {
		ts.ForEach(func(key string, node bindings.Node) {
			intf, ok := node.(*bindings.Interface)
			if !ok || !inputs[key] {
				return
			}
			for _, f := range intf.Fields {
				if omittable(f.Type) {
					f.QuestionToken = true
				}
			}
		})
	}
}

// omittable is null or unknown.
// Both decode an absent key: a pointer to nil, raw JSON to empty.
func omittable(t bindings.ExpressionType) bool {
	if k, ok := t.(*bindings.LiteralKeyword); ok {
		return *k == bindings.KeywordUnknown
	}
	u, ok := t.(*bindings.UnionType)
	if !ok {
		return false
	}
	for _, m := range u.Types {
		if _, isNull := m.(*bindings.Null); isNull {
			return true
		}
	}
	return false
}

// rename applies allowlisted TS names.
// It rewrites declarations and references alike, and records any reference
// to an API type the allowlist does not name.
func rename(pl plan, errs *[]error) guts.MutationFunc {
	return func(ts *guts.Typescript) {
		ts.ForEach(func(key string, node bindings.Node) {
			walk.Walk(&renamer{pl: pl, errs: errs, from: key}, node)
		})
	}
}

type renamer struct {
	pl   plan
	errs *[]error
	from string
}

func (r *renamer) Visit(node bindings.Node) walk.Visitor {
	switch n := node.(type) {
	case *bindings.Interface:
		r.apply(&n.Name, false)
	case *bindings.Alias:
		r.apply(&n.Name, false)
	case *bindings.ReferenceType:
		r.apply(&n.Name, true)
	case *bindings.LiteralKeyword:
		if *n == bindings.KeywordAny {
			*r.errs = append(*r.errs, fmt.Errorf("%s: any is not allowed", r.from))
		}
	}
	return r
}

func (r *renamer) apply(id *bindings.Identifier, ref bool) {
	if id.Package == nil || !strings.HasPrefix(id.Package.Path(), module+"/") {
		return
	}
	e, ok := r.pl.byGo[goKey{id.Package.Path(), id.Name}]
	if !ok {
		if ref {
			*r.errs = append(*r.errs, fmt.Errorf("%s references %s.%s, which is not allowlisted", r.from, id.Package.Path(), id.Name))
		}
		return
	}
	id.Name, id.Prefix = e.TS, ""
}
