"""Build the historical seed and its report.

Usage: uv run build_seed.py [--as-of YYYY-MM-DD]

Reads out/staged.json, out/products.json, out/pos.json, out/invoices.json
and the decisions in local/ (impa_enrichment.json and vendor_overrides.json
when present); writes apps/api/db/seeds/03_historical.sql (the same bytes
on every run), out/seed_report.md and out/review_vendors.csv. The rules
live in seed_model.py, the SQL in seed_sql.py; verify_seed.py checks a
loaded database against both.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from decimal import Decimal
from pathlib import Path

from paths import (
    ENRICHMENT_FILE,
    INVOICES_FILE,
    MANIFEST_FILE,
    OUT_DIR,
    OVERRIDES_FILE,
    POS_FILE,
    PRODUCTS_FILE,
    SEED_FILE,
    STAGED_FILE,
    VENDOR_OVERRIDES_FILE,
    data_dir,
)
from seed_model import PAID_BEFORE, Model, SeedError, build, rupiah
from seed_sql import render
from vendors import review_pairs, write_review

REPORT_FILE = OUT_DIR / "seed_report.md"
VENDOR_REVIEW_FILE = OUT_DIR / "review_vendors.csv"
SOURCE_DIRS = ("Quotation", "PO", "Invoice")
# Hand-made decisions the pipeline reads, kept only on the operator's machine.
LOCAL_INPUTS = (MANIFEST_FILE, OVERRIDES_FILE, VENDOR_OVERRIDES_FILE, ENRICHMENT_FILE)
BUILD_INPUTS = (STAGED_FILE, PRODUCTS_FILE, POS_FILE, INVOICES_FILE)
STATUSES = ("draft", "sent", "accepted", "revision", "cancelled")


def table_counts(model: Model) -> dict[str, int]:
    """Rows per table after a load; verify_seed.py compares the database."""
    q_history = sum(len(q.history) for q in model.quotations)
    return {
        "company_client": len(model.clients),
        "company_contacts": len(model.contacts),
        "vendors": len(model.vendors),
        "items": len(model.products),
        "vendor_products": len(model.links),
        "quotations": len(model.quotations),
        "quotation_items": sum(len(q.lines) for q in model.quotations),
        "quotation_status_history": q_history,
        "quotation_item_requests": 0,
        "item_request_matches": 0,
        "item_images": 0,
        "purchase_orders": len(model.pos),
        "purchase_order_items": sum(len(p.lines) for p in model.pos),
        "po_status_history": sum(len(p.history) for p in model.pos),
        "invoices": len(model.invoices),
        "invoice_items": sum(len(i.lines) for i in model.invoices),
        "invoice_status_history": sum(len(i.history) for i in model.invoices),
    }


def cell(value: object) -> str:
    return str(value if value is not None else "").replace("|", "\\|").replace("\n", " ")


def row(*values: object) -> str:
    return "| " + " | ".join(cell(v) for v in values) + " |"


def report(model: Model) -> str:
    out = [
        "# Historical seed report",
        "",
        "Generated by `apps/api/db/import/build_seed.py`. The seed is "
        "`apps/api/db/seeds/03_historical.sql`.",
        "",
        "## Rows per table",
        "",
        "| Table | Rows |",
        "|---|---|",
    ]
    out += [row(t, n) for t, n in table_counts(model).items()]
    unused = sum(1 for p in model.products if not p.used)
    enriched = sum(1 for p in model.products if p.impa_source == "enrichment")
    out += [
        "",
        f"Products: {len(model.products)} from products.json, {enriched} IMPA codes from "
        f"impa_enrichment.json, {unused} referenced by no imported line (their only "
        "quotations were skipped).",
        "",
        "## Quotations per year and status",
        "",
        "| Year | " + " | ".join(STATUSES) + " | Total |",
        "|---" * (len(STATUSES) + 2) + "|",
    ]
    by_year: Counter[tuple[int, str]] = Counter((q.date.year, q.status) for q in model.quotations)
    for year in sorted({y for y, _ in by_year}):
        counts = [by_year[(year, s)] for s in STATUSES]
        out.append(row(year, *counts, sum(counts)))
    origins = Counter(q.origin for q in model.quotations)
    paid = sum(1 for inv in model.invoices if inv.status == "paid")
    out += [
        "",
        f"Of these, {origins['synthetic']} are rebuilt from client PO lines (no quotation in "
        "the files) and the rest come from out/staged.json. Revisions keep their base number "
        "with ` Rev.n`.",
        "",
        f"Invoices: {paid} paid (dated before {PAID_BEFORE}, paid on the due date), "
        f"{len(model.invoices) - paid} sent.",
        "",
        "## Skipped quotations",
        "",
        "| Original number | Reason |",
        "|---|---|",
    ]
    out += [row(n, r) for n, r in model.skipped]
    out += ["", "## Flagged records", "", "| Record | Detail |", "|---|---|"]
    out += [row(n, r) for n, r in model.flagged]
    out += reconciliation(model)
    out += mapping(model)
    return "\n".join(out) + "\n"


def reconciliation(model: Model) -> list[str]:
    match = differ = none = 0
    rows: list[str] = []
    missing: list[str] = []
    for q in model.quotations:
        assert q.totals is not None
        if q.printed_grand is None:
            none += 1
            missing.append(row(q.number, q.original, q.origin, rupiah(q.totals.grand)))
            continue
        diff = q.totals.grand - q.printed_grand
        if abs(diff) <= 1:
            match += 1
            continue
        differ += 1
        rows.append(
            row(
                q.number,
                q.original,
                rupiah(q.printed_grand),
                rupiah(q.totals.grand),
                rupiah(diff),
                "; ".join(q.causes),
            )
        )
    inv_total = sum((i.total for i in model.invoices), Decimal(0))
    return [
        "",
        "## Reconciliation",
        "",
        "Quotation totals follow the app's arithmetic (per-line DPP Nilai Lain and PPN, "
        "fn_recompute_quotation_totals), so they are compared with the printed grand total.",
        "",
        f"- Within Rp 1 of the printed grand total: {match}",
        f"- Differing by more than Rp 1 (printed total in the notes): {differ}",
        f"- No printed total to compare: {none}",
        f"- Invoices: {len(model.invoices)}, every header stored as printed "
        f"(sum of totals {rupiah(inv_total)}); verify_seed.py checks them in the database.",
        "",
        "### Quotations that differ from their printed total",
        "",
        "| Number | Original | Printed | Stored | Stored - printed | Cause |",
        "|---|---|---|---|---|---|",
        *rows,
        "",
        "### Quotations without a printed total",
        "",
        "| Number | Original | Origin | Stored |",
        "|---|---|---|---|",
        *missing,
    ]


def mapping(model: Model) -> list[str]:
    out = [
        "",
        "## Number mapping",
        "",
        "### Quotations",
        "",
        "| New number | Original | Date | Client | Status | Source |",
        "|---|---|---|---|---|---|",
    ]
    out += [
        row(q.number, q.original, q.date, q.client.name, q.status, q.source)
        for q in model.quotations
    ]
    out += [
        "",
        "### Purchase orders and delivery notes",
        "",
        "| PO id | Client PO number | PO date | Quotation | Delivery note | Original DO |",
        "|---|---|---|---|---|---|",
    ]
    out += [
        row(
            po.key,
            po.number or f"(none: {po.missing_reason})",
            po.po_date,
            po.quotation.number,
            po.dn_number,
            po.dn_original,
        )
        for po in model.pos
    ]
    out += [
        "",
        "### Invoices",
        "",
        "| New number | Original | Date | PO | Total |",
        "|---|---|---|---|---|",
    ]
    out += [
        row(inv.number, inv.original, inv.invoice_date, inv.po.key, rupiah(inv.total))
        for inv in model.invoices
    ]
    return out


def missing_sources() -> list[str]:
    """What the full pipeline needs and this machine lacks."""
    root = data_dir()
    missing = [
        f"{root / sub} (set GNS_DATA_DIR)" for sub in SOURCE_DIRS if not (root / sub).is_dir()
    ]
    return missing + [str(p) for p in LOCAL_INPUTS if not p.is_file()]


def missing_outputs() -> list[str]:
    """Pipeline outputs this build reads."""
    return [str(p) for p in BUILD_INPUTS if not p.is_file()]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--seed", type=Path, default=SEED_FILE)
    ap.add_argument("--report", type=Path, default=REPORT_FILE)
    ap.add_argument(
        "--check-sources", action="store_true", help="only check that Data/ and local/ are here"
    )
    args = ap.parse_args(argv)
    missing = missing_sources()
    if not args.check_sources:
        missing += missing_outputs()
    for m in missing:
        print(f"build_seed: missing {m}", file=sys.stderr)
    if missing:
        print(
            "build_seed: the seed is built on this machine from Data/ and the hand-made "
            "decisions in db/import/local/, which are never committed; restore them from "
            "their backup and run `make seed-build` (apps/api/db/import/README.md)",
            file=sys.stderr,
        )
        return 1
    if args.check_sources:
        return 0
    try:
        model = build()
    except SeedError as exc:
        print(f"build_seed: {exc}", file=sys.stderr)
        return 1
    args.seed.write_text(render(model), encoding="utf-8")
    args.report.write_text(report(model), encoding="utf-8")
    pairs = review_pairs({v.key: v.names for v in model.vendors})
    write_review(pairs, VENDOR_REVIEW_FILE)
    counts = table_counts(model)
    print(
        f"{args.seed}: {counts['quotations']} quotations, {counts['purchase_orders']} POs, "
        f"{counts['invoices']} invoices; report {args.report}; "
        f"{len(pairs)} vendor pairs to review in {VENDOR_REVIEW_FILE.name}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
