"""Write the seed model as one deterministic SQL script.

The script is apps/api/db/seeds/03_historical.sql. It loads into a
database migrated to 00100 with 01_master.sql applied and every business
table empty, inside one transaction: its own when run alone (make
seed-dev), or the caller's when replace_business_data.sql sets
gns_outer_tx and includes it.

Rows carry explicit ids so documents can reference each other; the
acting user is the oldest active superadmin, looked up in SQL. Totals
come from the app's own fn_recompute_quotation_totals; filed invoices
keep the amounts printed on them.
"""

from __future__ import annotations

import json
from collections.abc import Iterable, Sequence
from datetime import date, datetime
from decimal import Decimal

from seed_model import PAID_BEFORE, WIB, Model, Quotation, at

CHUNK = 500

# Business tables the seed fills; the load refuses unless all are empty.
BUSINESS_TABLES = (
    "company_client",
    "company_contacts",
    "vendors",
    "items",
    "vendor_products",
    "item_images",
    "item_request_matches",
    "quotations",
    "quotation_items",
    "quotation_item_requests",
    "quotation_status_history",
    "quotation_edit_locks",
    "purchase_orders",
    "purchase_order_items",
    "po_status_history",
    "invoices",
    "invoice_items",
    "invoice_status_history",
)

# Tables whose id sequence the load moves past the loaded rows.
ID_TABLES = tuple(t for t in BUSINESS_TABLES if t != "quotation_edit_locks")

Col = tuple[str, str]
Value = object


def lit(value: Value) -> str:
    """One SQL literal."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, Decimal):
        return format(value, "f")
    if isinstance(value, datetime):
        return "'" + value.astimezone(WIB).strftime("%Y-%m-%d %H:%M:%S+07") + "'"
    if isinstance(value, date):
        return f"'{value.isoformat()}'"
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    if isinstance(value, dict):
        return lit(json.dumps(value, ensure_ascii=False, sort_keys=True))
    raise TypeError(f"no SQL literal for {type(value).__name__}")


def insert(
    table: str,
    cols: Sequence[Col],
    rows: Iterable[Sequence[Value]],
    extra: Sequence[tuple[str, str]] = (),
    actor: Sequence[str] = ("created_by", "updated_by"),
    joins: str = "",
) -> str:
    """INSERT ... SELECT over VALUES, with the actor joined in."""
    rows = list(rows)
    if not rows:
        return f"-- {table}: no rows\n"
    targets = [c for c, _ in cols if not c.startswith("_")]
    exprs = [f"v.{c}::{t}" for c, t in cols if not c.startswith("_")]
    targets += [t for t, _ in extra] + list(actor)
    exprs += [e for _, e in extra] + ["s.id"] * len(actor)
    names = ", ".join(c for c, _ in cols)
    order = f"v.{cols[0][0]}::{cols[0][1]}"
    out: list[str] = []
    for start in range(0, len(rows), CHUNK):
        body = ",\n".join(
            "  (" + ", ".join(lit(v) for v in r) + ")" for r in rows[start : start + CHUNK]
        )
        out.append(
            f"INSERT INTO {table} ({', '.join(targets)})\n"
            f"SELECT {', '.join(exprs)}\n"
            f"FROM (VALUES\n{body}\n) AS v({names})\n"
            f"CROSS JOIN seed_actor s\n{joins}ORDER BY {order};\n"
        )
    return "\n".join(out)


def contact_info(phone: str | None) -> dict[str, str] | None:
    """vendors.contact_info: the keys ContactInfo reads, blanks left out."""
    return {"phone": phone} if phone else None


def unit_id(col: str) -> str:
    return f"(SELECT u.id FROM units u WHERE u.code = v.{col})"


def header(model: Model) -> str:
    return (
        "-- HISTORICAL IMPORT, generated by apps/api/db/import/build_seed.py.\n"
        "-- Do not edit by hand: change the inputs or the rules and rebuild.\n"
        f"-- {len(model.quotations)} quotations, {len(model.pos)} purchase orders, "
        f"{len(model.invoices)} invoices; invoices dated before {PAID_BEFORE} are paid.\n"
        "-- Loads into empty business tables (make seed-dev) or inside\n"
        "-- replace_business_data.sql (make reimport-dev), in one transaction.\n\n"
        "\\set ON_ERROR_STOP on\n"
        "\\if :{?gns_outer_tx}\n\\else\nBEGIN;\n\\endif\n\n"
    )


def guards(model: Model) -> str:
    units = sorted(
        {ln.unit for q in model.quotations for ln in q.lines if ln.unit}
        | {ln.unit for po in model.pos for ln in po.lines if ln.unit}
        | {ln.unit for inv in model.invoices for ln in inv.lines if ln.unit}
        | {p.unit for p in model.products if p.unit}
    )
    empty = "\n".join(
        f"  IF EXISTS (SELECT 1 FROM {t}) THEN\n"
        f"    RAISE EXCEPTION 'historical seed: {t} is not empty. "
        "Replace business data with make reimport-dev (dev) or "
        "replace_business_data.sql (prod).';\n  END IF;"
        for t in BUSINESS_TABLES
    )
    return (
        "-- Guards\n"
        "CREATE TEMP TABLE seed_actor ON COMMIT DROP AS\n"
        "SELECT id FROM users WHERE role = 'superadmin' AND is_active\n"
        "ORDER BY created_at, id LIMIT 1;\n\n"
        "DO $$\nBEGIN\n"
        "  IF NOT COALESCE((SELECT is_applied FROM goose_db_version\n"
        "                   WHERE version_id = 100 ORDER BY id DESC LIMIT 1), FALSE) THEN\n"
        "    RAISE EXCEPTION 'historical seed: migration 00100 is not applied';\n  END IF;\n"
        "  IF NOT EXISTS (SELECT 1 FROM seed_actor) THEN\n"
        "    RAISE EXCEPTION 'historical seed: no active superadmin to own the rows';\n"
        "  END IF;\n"
        f"  IF EXISTS (SELECT unnest(ARRAY[{', '.join(lit(u) for u in units)}])\n"
        "             EXCEPT SELECT code FROM units) THEN\n"
        "    RAISE EXCEPTION 'historical seed: a unit code is missing; load 01_master.sql';\n"
        f"  END IF;\n{empty}\nEND $$;\n\n"
    )


def masters(model: Model) -> str:
    parts = ["-- Clients, contacts, vendors, products\n"]
    parts.append(
        insert(
            "company_client",
            [
                ("id", "bigint"),
                ("number", "text"),
                ("name", "text"),
                ("address", "text"),
                ("npwp", "text"),
                ("created_at", "timestamptz"),
            ],
            [(c.id, c.number, c.name, c.address, c.npwp, at(c.first_date)) for c in model.clients],
            extra=[("country_code", "'IDN'"), ("updated_at", "v.created_at::timestamptz")],
        )
    )
    parts.append(
        insert(
            "company_contacts",
            [
                ("id", "bigint"),
                ("company_id", "bigint"),
                ("name", "text"),
                ("email", "text"),
                ("phone", "text"),
                ("created_at", "timestamptz"),
            ],
            [
                (c.id, c.client.id, c.name, c.email, c.phone, at(c.first_date))
                for c in model.contacts
            ],
            extra=[("country_code", "'IDN'"), ("updated_at", "v.created_at::timestamptz")],
        )
    )
    parts.append(
        insert(
            "vendors",
            [
                ("id", "bigint"),
                ("name", "text"),
                ("location", "text"),
                ("contact_info", "jsonb"),
                ("created_at", "timestamptz"),
            ],
            [
                (v.id, v.name, v.location, contact_info(v.phone), at(v.first_date))
                for v in model.vendors
            ],
            extra=[("updated_at", "v.created_at::timestamptz")],
        )
    )
    parts.append(
        insert(
            "items",
            [
                ("id", "bigint"),
                ("name", "text"),
                ("description", "text"),
                ("impa_code", "text"),
                ("_unit", "text"),
                ("created_at", "timestamptz"),
            ],
            [
                (p.id, p.name, p.description, p.impa, p.unit, at(p.first_date))
                for p in model.products
            ],
            extra=[
                ("default_unit_id", unit_id("_unit")),
                ("updated_at", "v.created_at::timestamptz"),
            ],
        )
    )
    parts.append(
        insert(
            "vendor_products",
            [
                ("id", "bigint"),
                ("vendor_id", "bigint"),
                ("item_id", "bigint"),
                ("cost_price", "numeric"),
                ("last_quoted_at", "timestamptz"),
                ("created_at", "timestamptz"),
            ],
            [
                (lk.id, lk.vendor.id, lk.product.id, lk.cost, at(lk.last_date), at(lk.first_date))
                for lk in model.links
            ],
            extra=[("updated_at", "v.last_quoted_at::timestamptz")],
        )
    )
    return "\n".join(parts)


def notes(q: Quotation) -> str | None:
    return "\n".join(q.notes) or None


def quotations(model: Model) -> str:
    qs = model.quotations
    parts = [
        "-- Quotations\n"
        "-- trg_quotations_updated_at stamps NOW() on every update. The totals\n"
        "-- below are written by the app's fn_recompute_quotation_totals, an\n"
        "-- update, and updated_at must end as the last status move, so the\n"
        "-- trigger is off for this block and back on before it ends.\n"
        "ALTER TABLE quotations DISABLE TRIGGER trg_quotations_updated_at;\n"
    ]
    parts.append(
        insert(
            "quotations",
            [
                ("id", "bigint"),
                ("quotation_no", "text"),
                ("version", "integer"),
                ("parent_id", "bigint"),
                ("company_client_id", "bigint"),
                ("company_client_name", "text"),
                ("contact_id", "bigint"),
                ("contact_name", "text"),
                ("client_ref_no", "text"),
                ("vessel_name", "text"),
                ("status", "text"),
                ("notes", "text"),
                ("payment_terms", "text"),
                ("validity_days", "smallint"),
                ("discount_pct", "numeric"),
                ("legacy_no", "text"),
                ("created_at", "timestamptz"),
            ],
            [
                (
                    q.id,
                    q.number,
                    q.version,
                    q.parent.id if q.parent else None,
                    q.client.id,
                    q.client.name,
                    q.contact.id if q.contact else None,
                    q.contact_name,
                    q.client_ref,
                    q.vessel,
                    q.status,
                    notes(q),
                    q.payment_terms,
                    q.validity_days,
                    q.discount_pct,
                    q.legacy,
                    at(q.date),
                )
                for q in qs
            ],
            extra=[("updated_at", "v.created_at::timestamptz")],
        )
    )
    parts.append(
        insert(
            "quotation_items",
            [
                ("id", "bigint"),
                ("quotation_id", "bigint"),
                ("line_number", "smallint"),
                ("item_type", "text"),
                ("requested_impa", "text"),
                ("requested_name", "text"),
                ("offered_item_id", "bigint"),
                ("vendor_product_id", "bigint"),
                ("qty", "numeric"),
                ("_unit", "text"),
                ("selling_price", "numeric"),
                ("cost_price", "numeric"),
                ("is_available", "boolean"),
                ("ship_destination", "text"),
                ("shipping_days", "integer"),
                ("discount_pct", "numeric"),
                ("created_at", "timestamptz"),
            ],
            [
                (
                    ln.id,
                    q.id,
                    ln.line_number,
                    ln.item_type,
                    ln.requested_impa,
                    ln.requested_name,
                    ln.product.id if ln.product else None,
                    ln.link.id if ln.link else None,
                    ln.qty,
                    ln.unit,
                    ln.sell,
                    ln.cost,
                    ln.available,
                    ln.ship_destination,
                    ln.shipping_days,
                    q.discount_pct,
                    at(q.date),
                )
                for q in qs
                for ln in q.lines
            ],
            extra=[("unit_id", unit_id("_unit")), ("updated_at", "v.created_at::timestamptz")],
        )
    )
    parts.append(
        "DO $$\nBEGIN\n"
        "  PERFORM fn_recompute_quotation_totals(id) FROM quotations ORDER BY id;\n"
        "END $$;\n"
    )
    first = [(q.id, h.to_status, h.at, h.note) for q in qs for h in q.history[:1]]
    parts.append(
        "-- trg_log_quotation_creation logged each insert at NOW(); date it.\n"
        "UPDATE quotation_status_history h\n"
        "SET to_status = v.to_status, changed_at = v.changed_at::timestamptz, note = v.note\n"
        "FROM (VALUES\n"
        + ",\n".join("  (" + ", ".join(lit(x) for x in r) + ")" for r in first)
        + "\n) AS v(quotation_id, to_status, changed_at, note)\n"
        "WHERE h.quotation_id = v.quotation_id AND h.from_status IS NULL;\n"
    )
    moves = [
        (q.id, i, h.from_status, h.to_status, h.note, h.at)
        for q in qs
        for i, h in enumerate(q.history)
        if i > 0
    ]
    parts.append(history_insert("quotation_status_history", "quotation_id", moves))
    parts.append(
        "UPDATE quotations q SET updated_at = h.last\n"
        "FROM (SELECT quotation_id, max(changed_at) AS last\n"
        "      FROM quotation_status_history GROUP BY quotation_id) h\n"
        "WHERE h.quotation_id = q.id;\n"
        "ALTER TABLE quotations ENABLE TRIGGER trg_quotations_updated_at;\n"
    )
    return "\n".join(parts)


def history_insert(table: str, key: str, moves: list[tuple[Value, ...]]) -> str:
    """Status moves in order, each by the seed actor."""
    body = ",\n".join("  (" + ", ".join(lit(x) for x in r) + ")" for r in moves)
    return (
        f"INSERT INTO {table} ({key}, from_status, to_status, note, changed_by, changed_at)\n"
        f"SELECT v.{key}::bigint, v.from_status::text, v.to_status::text, v.note::text,\n"
        "       s.id, v.changed_at::timestamptz\n"
        f"FROM (VALUES\n{body}\n)\n"
        f"AS v({key}, step, from_status, to_status, note, changed_at)\n"
        f"CROSS JOIN seed_actor s\nORDER BY v.{key}::bigint, v.step::integer;\n"
    )


def purchase_orders(model: Model) -> str:
    parts = ["-- Purchase orders\n"]
    parts.append(
        insert(
            "purchase_orders",
            [
                ("id", "bigint"),
                ("po_number", "text"),
                ("quotation_id", "bigint"),
                ("company_client_id", "bigint"),
                ("contact_id", "bigint"),
                ("po_date", "date"),
                ("status", "text"),
                ("delivery_note_number", "text"),
                ("delivery_note_date", "date"),
                ("legacy_dn_no", "text"),
                ("notes", "text"),
                ("discount_pct", "numeric"),
                ("created_at", "timestamptz"),
                ("updated_at", "timestamptz"),
            ],
            [
                (
                    po.id,
                    po.number,
                    po.quotation.id,
                    po.client.id,
                    po.quotation.contact.id if po.quotation.contact else None,
                    po.po_date,
                    po.history[-1].to_status,
                    po.dn_number,
                    po.dn_date,
                    po.dn_original,
                    "\n".join(po.notes) or None,
                    po.discount_pct,
                    at(po.po_date),
                    po.history[-1].at,
                )
                for po in model.pos
            ],
        )
    )
    parts.append(
        insert(
            "purchase_order_items",
            [
                ("id", "bigint"),
                ("po_id", "bigint"),
                ("quotation_item_id", "bigint"),
                ("line_number", "smallint"),
                ("item_type", "text"),
                ("offered_item_id", "bigint"),
                ("vendor_product_id", "bigint"),
                ("qty", "numeric"),
                ("_unit", "text"),
                ("selling_price", "numeric"),
                ("cost_price", "numeric"),
                ("discount_pct", "numeric"),
                ("item_name", "text"),
                ("item_code", "text"),
                ("ship_destination", "text"),
                ("shipping_days", "integer"),
                ("created_at", "timestamptz"),
            ],
            [
                (
                    ln.id,
                    po.id,
                    ln.quotation_item_id,
                    ln.line_number,
                    ln.item_type,
                    ln.product.id if ln.product else None,
                    ln.link.id if ln.link else None,
                    ln.qty,
                    ln.unit,
                    ln.sell,
                    ln.cost,
                    po.discount_pct,
                    ln.item_name,
                    ln.item_code,
                    ln.ship_destination,
                    ln.shipping_days,
                    at(po.po_date),
                )
                for po in model.pos
                for ln in po.lines
            ],
            extra=[("unit_id", unit_id("_unit")), ("updated_at", "v.created_at::timestamptz")],
        )
    )
    first = [(po.id, po.history[0].to_status, po.history[0].at) for po in model.pos]
    parts.append(
        "-- trg_log_po_creation logged each insert at NOW(); date it.\n"
        "UPDATE po_status_history h\n"
        "SET to_status = v.to_status, changed_at = v.changed_at::timestamptz\n"
        "FROM (VALUES\n"
        + ",\n".join("  (" + ", ".join(lit(x) for x in r) + ")" for r in first)
        + "\n) AS v(po_id, to_status, changed_at)\n"
        "WHERE h.po_id = v.po_id AND h.from_status IS NULL;\n"
    )
    moves = [
        (po.id, i, h.from_status, h.to_status, h.note, h.at)
        for po in model.pos
        for i, h in enumerate(po.history)
        if i > 0
    ]
    parts.append(history_insert("po_status_history", "po_id", moves))
    return "\n".join(parts)


def invoices(model: Model) -> str:
    parts = ["-- Invoices, with the amounts printed on them\n"]
    parts.append(
        insert(
            "invoices",
            [
                ("id", "bigint"),
                ("invoice_no", "text"),
                ("quotation_id", "bigint"),
                ("po_id", "bigint"),
                ("company_client_id", "bigint"),
                ("invoice_date", "date"),
                ("due_date", "date"),
                ("subtotal", "numeric"),
                ("dpp", "numeric"),
                ("dpp_nilai_lain", "numeric"),
                ("ppn_amount", "numeric"),
                ("total", "numeric"),
                ("total_discount", "numeric"),
                ("legacy_no", "text"),
                ("buyer_name", "text"),
                ("buyer_npwp", "text"),
                ("buyer_address", "text"),
                ("status", "text"),
                ("paid_at", "timestamptz"),
                ("created_at", "timestamptz"),
                ("updated_at", "timestamptz"),
            ],
            [
                (
                    inv.id,
                    inv.number,
                    inv.po.quotation.id,
                    inv.po.id,
                    inv.po.client.id,
                    inv.invoice_date,
                    inv.due_date,
                    inv.subtotal,
                    inv.dpp,
                    inv.dpp_nilai_lain,
                    inv.ppn,
                    inv.total,
                    inv.total_discount,
                    inv.original,
                    inv.buyer_name,
                    inv.buyer_npwp,
                    inv.buyer_address,
                    inv.status,
                    inv.paid_at,
                    at(inv.invoice_date),
                    inv.history[-1].at,
                )
                for inv in model.invoices
            ],
            extra=[("ppn_rate", "12.00")],
        )
    )
    parts.append(
        insert(
            "invoice_items",
            [
                ("id", "bigint"),
                ("invoice_id", "bigint"),
                ("quotation_item_id", "bigint"),
                ("line_type", "text"),
                ("line_number", "smallint"),
                ("item_name", "text"),
                ("item_code", "text"),
                ("goods_or_service", "text"),
                ("unit_code", "text"),
                ("qty", "numeric"),
                ("unit_price", "numeric"),
                ("gross_unit_price", "numeric"),
                ("dpp", "numeric"),
                ("dpp_nilai_lain", "numeric"),
                ("ppn_rate", "numeric"),
                ("ppn_amount", "numeric"),
                ("offered_item_id", "bigint"),
                ("cost_price", "numeric"),
                ("created_at", "timestamptz"),
            ],
            [
                (
                    ln.id,
                    inv.id,
                    ln.po_line.quotation_item_id,
                    ln.line_type,
                    ln.line_number,
                    ln.item_name,
                    ln.item_code,
                    ln.goods_or_service,
                    ln.unit,
                    ln.qty,
                    ln.unit_price,
                    ln.gross_unit_price,
                    ln.dpp,
                    ln.dpp_nilai_lain,
                    ln.ppn_rate,
                    ln.ppn,
                    ln.po_line.product.id if ln.po_line.product else None,
                    ln.po_line.cost,
                    at(inv.invoice_date),
                )
                for inv in model.invoices
                for ln in inv.lines
            ],
            extra=[("unit_id", unit_id("unit_code"))],
        )
    )
    moves = [
        (inv.id, i, h.from_status, h.to_status, h.note, h.at)
        for inv in model.invoices
        for i, h in enumerate(inv.history)
    ]
    parts.append(history_insert("invoice_status_history", "invoice_id", moves))
    return "\n".join(parts)


def counters(model: Model) -> str:
    q = max((x.seq for x in model.quotations), default=0)
    inv = max((x.seq for x in model.invoices), default=0)
    dn = max((x.dn_seq for x in model.pos), default=0)
    resets = "\n".join(
        f"  PERFORM setval(pg_get_serial_sequence('{t}', 'id'),"
        f" COALESCE((SELECT max(id) FROM {t}), 0) + 1, false);"
        for t in ID_TABLES
    )
    return (
        "-- Numbering continues after the highest loaded number\n"
        f"UPDATE doc_counters SET last_seq = CASE doc_type WHEN 'Q' THEN {q}"
        f" WHEN 'INV' THEN {inv} WHEN 'DN' THEN {dn} END, updated_at = NOW();\n\n"
        "-- Id sequences past the loaded rows\n"
        f"DO $$\nBEGIN\n{resets}\n"
        "  PERFORM setval('company_client_number_seq',"
        " (SELECT max(number::integer) FROM company_client));\n"
        "END $$;\n"
    )


def render(model: Model) -> str:
    """The whole seed script."""
    return "\n".join(
        [
            header(model),
            guards(model),
            masters(model),
            quotations(model),
            purchase_orders(model),
            invoices(model),
            counters(model),
            "\\if :{?gns_outer_tx}\n\\else\nCOMMIT;\n\\endif\n",
        ]
    )
