// Generated by make gen-types.
//
// Source: the Go DTOs allowlisted in apps/api/cmd/gentypes. Do not edit;
// change the Go type and regenerate. Three rules shape the output:
// - A response field tagged omitempty is optional and never null, since Go
//   drops the key instead of sending null.
// - A request (Input) field that Go reads through a pointer is optional,
//   since Go decodes an absent key as nil.
// - Slices and maps are typed non-null; a handler must send them empty,
//   never nil.

// From items/dto.go
export type AddVendorToItemInput = {
    vendorId: number;
    vendorSku?: string | null;
    costPrice?: string | null;
    productUrl?: string | null;
};

// From items/dto.go
export type AdvancedSearchHit = {
    id: number;
    name: string;
    impaCode?: string;
    defaultUnitId?: number;
    isActive: boolean;
    score: number;
    tier: string;
    tiers: string[];
    vendorId?: number;
    vendorName?: string;
    vendorSku?: string;
    requestText?: string;
    imageObjectKey?: string;
};

// From items/dto.go
export type AdvancedSearchResponse = {
    query: string;
    total: number;
    hits: AdvancedSearchHit[];
    counts: Record<string, number>;
};

// From invoices/dto.go
export type ChangeInvoiceStatusInput = {
    status: InvoiceBackendStatus;
    note?: string;
    paymentProofKey?: string;
};

// From auth/dto.go
export type ChangeOwnPasswordInput = {
    currentPassword: string;
    newPassword: string;
};

// From users/dto.go
export type ChangeUserPasswordInput = {
    password: string;
};

// From clients/dto.go
export type ClientQuotationRow = {
    id: number;
    quotationNo: string;
    createdAt: string;
    status: string;
    contactName?: string;
    grandTotal: string;
    productCount: number;
};

// From clients/dto.go
export type ClientRow = {
    id: number;
    number?: string;
    name: string;
    npwp?: string;
    address?: string;
    email?: string;
    countryCode: string;
    tkuId?: string;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
    contactId?: number;
    contactName?: string;
    contactEmail?: string;
    contactPhone?: string;
    totalPurchase: string;
    quotationCount: number;
    logoObjectKey?: string;
};

// From clients/dto.go
export type ClientSearchHit = {
    companyId: number;
    companyName: string;
    companyNumber?: string;
    companyNpwp?: string;
    companyAddress?: string;
    companyEmail?: string;
    companyCountry: string;
    companyTku?: string;
    contactId?: number;
    contactName?: string;
    contactEmail?: string;
    contactPhone?: string;
    contactTitle?: string;
    score: number;
    matchTier: string;
};

// From clients/dto.go
export type ClientSummary = {
    total: number;
    activeCount: number;
    newThisMonth: number;
    newThisYear: number;
    prevYearTotal: number;
};

// From clients/dto.go
export type ContactRow = {
    id: number;
    companyId: number;
    name: string;
    email?: string;
    phone?: string;
    title?: string;
    countryCode: string;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
};

// From countries/dto.go
export type CountryRow = {
    code: string;
    name: string;
    dialCode: string;
};

// From clients/dto.go
export type CreateClientInput = {
    number?: string | null;
    name: string;
    npwp?: string | null;
    address?: string | null;
    email?: string | null;
    countryCode?: string;
    tkuId?: string | null;
};

// From clients/dto.go
export type CreateContactInput = {
    name: string;
    email?: string | null;
    phone?: string | null;
    title?: string | null;
    countryCode?: string;
};

// From items/dto.go
export type CreateItemInput = {
    name: string;
    impaCode?: string | null;
    defaultUnitId?: number | null;
    description?: string | null;
    isActive?: boolean | null;
};

// From users/dto.go
export type CreateUserInput = {
    email: string;
    name: string;
    password: string;
    role: Role;
    isActive?: boolean;
};

// From vendors/dto.go
export type CreateVendorInput = {
    name: string;
    location?: string | null;
    contactInfo?: VendorContactInfo | null;
    isActive?: boolean | null;
};

// From dashboard/dto.go
export type DashboardStatusCount = {
    status: string;
    label: string;
    count: number;
};

// From dashboard/dto.go
export type DashboardSummary = {
    totalRevenue: string;
    totalExpenses: string;
    totalProfit: string;
    totalPpn: string;
    totalQuotations: number;
    totalQuotationsRejected: number;
    totalPo: number;
    totalInvoices: number;
    totalInvoicesPaid: number;
    invoicesDueSoon: number;
    invoicesOverdue: number;
    quotationStatuses: DashboardStatusCount[];
    poStatuses: DashboardStatusCount[];
    invoiceStatuses: DashboardStatusCount[];
};

// From dashboard/dto.go
export type DashboardTimeseriesPoint = {
    month: string;
    value: string;
};

// From invoices/dto.go
export type InvoiceBackendRow = {
    id: number;
    invoiceNo: string;
    legacyNo?: string;
    quotationId: number;
    quotationNo: string;
    poId?: number;
    companyClientId: number;
    companyName: string;
    companyNpwp?: string;
    companyAddress?: string;
    invoiceDate: string;
    dueDate?: string;
    subtotal?: string;
    totalDiscount?: string;
    dpp?: string;
    dppNilaiLain?: string;
    ppnAmount?: string;
    total?: string;
    status: InvoiceBackendStatus;
    effectiveStatus: InvoiceBackendStatus;
    taxTransactionCode?: string;
    fakturType?: string;
    rowVersion: number;
    createdAt: string;
    updatedAt: string;
    attachmentObjectKey?: string;
    paidAt?: string;
    paymentProofKey?: string;
};

// From invoices/dto.go
export type InvoiceBackendStatus = "cancelled" | "draft" | "overdue" | "paid" | "sent";

// From invoices/dto.go
export type InvoiceDatesSaved = {
    rowVersion: number;
};

// From invoices/dto.go
export type InvoiceDetail = InvoiceBackendRow & {
    vesselName?: string;
    poNumber?: string;
    poDate?: string;
    companyEmail?: string;
    companyCountryCode: string;
    companyTkuId?: string;
    contactName?: string;
    contactEmail?: string;
    contactPhone?: string;
    replacesInvoiceId?: number;
    replacesInvoiceNo?: string;
    replacedByInvoiceId?: number;
    allowedTransitions: InvoiceTransition[];
    canReplace: boolean;
    history: InvoiceStatusEvent[];
};

// From invoices/dto.go
export type InvoiceItemRow = {
    id: number;
    invoiceId: number;
    lineNumber?: number;
    lineType: string;
    itemCode?: string;
    itemName: string;
    offeredItemId?: number;
    unitId?: number;
    unitCode?: string;
    unitCoretaxCode?: string;
    qty: string;
    unitPrice: string;
    grossUnitPrice?: string;
    costPrice?: string;
    dpp?: string;
    dppNilaiLain?: string;
    ppnRate?: string;
    ppnAmount?: string;
    shipDestination?: string;
    goodsOrService?: string;
};

// From invoices/dto.go
export type InvoiceStatusEvent = {
    id: number;
    fromStatus: InvoiceBackendStatus;
    toStatus: InvoiceBackendStatus;
    note?: string;
    paymentProofKey?: string;
    changedBy: number;
    changedAt: string;
};

// From invoices/dto.go
export type InvoiceSummary = {
    total: number;
    draft: number;
    sent: number;
    paid: number;
    overdue: number;
};

// From invoices/transitions.go
export type InvoiceTransition = {
    to: InvoiceBackendStatus;
    label: string;
    requiresNote: boolean;
};

// From items/dto.go
export type ItemGallery = {
    max: number;
    images: ItemImage[];
};

// From items/dto.go
export type ItemImage = {
    id: number;
    objectKey: string;
    isCover: boolean;
    downloadUrl: string;
};

// From items/dto.go
export type ItemPriceHistoryRow = {
    quotationNo: string;
    quotationDate: string;
    clientName: string;
    qty: string;
    costPrice?: string;
    sellingPrice: string;
    profitPct?: string;
};

// From items/dto.go
export type ItemQuotationRow = {
    lineId: number;
    quotationId: number;
    quotationNo: string;
    quotationDate: string;
    status: string;
    clientId: number;
    clientName: string;
    contactName?: string;
    vendorId?: number;
    vendorName?: string;
    qty: string;
    costPrice?: string;
    sellingPrice: string;
};

// From items/dto.go
export type ItemRow = {
    id: number;
    name: string;
    impaCode?: string;
    defaultUnitId?: number;
    description?: string;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
    imageObjectKey?: string;
};

// From items/dto.go
export type ItemVendorRow = {
    vendorProductId: number;
    vendorId: number;
    vendorName: string;
    vendorSku?: string;
    costPrice?: string;
    productUrl?: string;
    lastQuotedAt?: string;
};

// From items/dto.go
export type LineRecommendation = {
    itemId: number;
    vendorProductId?: number;
    vendorId?: number;
    vendorName?: string;
    costPrice?: string;
    sellingPrice?: string;
};

// From auth/dto.go
export type LoginInput = {
    email: string;
    password: string;
};

// From auth/dto.go
export type LoginResponse = {
    token: string;
    expiresAt: number;
    user: MeUser;
};

// From items/dto.go
export type MatchRowInput = {
    impaCode: string;
    name: string;
    qty: number;
    unit: string;
};

// From items/dto.go
export type MatchRowResult = {
    index: number;
    requested: MatchRowInput;
    matched?: MatchedItemWithVendor;
    confidence: number;
    source: string;
};

// From items/dto.go
export type MatchRowsInput = {
    rows: MatchRowInput[];
    minScore?: number;
    autoCreate?: boolean;
};

// From items/dto.go
export type MatchRowsResponse = {
    rows: MatchRowResult[];
};

// From items/dto.go
export type MatchedItemWithVendor = {
    itemId: number;
    itemName: string;
    impaCode?: string;
    defaultUnitId?: number;
    defaultUnitCode?: string;
    vendorProductId?: number;
    vendorId?: number;
    vendorName?: string;
    costPrice?: string;
};

// From auth/dto.go
export type MeUser = {
    id: number;
    email: string;
    name: string;
    role: Role;
};

// From assetproxy/assetproxy.go
export type ObjectKeyInput = {
    objectKey: string;
};

// From purchaseorders/dto.go
export type PoBackendStatus = "CANCELLED" | "DELIVERED" | "ON_PROGRESS" | "PENDING" | "UPLOADED";

// From purchaseorders/completeness.go
export type PoCompletenessGap = {
    code: PoGapCode;
    label: string;
};

// From purchaseorders/completeness.go
export type PoCompletenessIssue = {
    kind: PoIssueKind;
    id: number;
    name?: string;
    message: string;
    missing: PoCompletenessGap[];
};

// From purchaseorders/dto.go
export type PoDetailsInput = {
    poNumber: string;
    poDate: string;
};

// From purchaseorders/dto.go
export type PoFileInput = {
    fileName: string;
    fileSize: number;
    objectKey: string;
};

// From purchaseorders/completeness.go
export type PoGapCode = "client_address" | "client_npwp" | "client_number" | "contact_inactive" | "contact_name" | "contact_reach" | "po_number" | "shipping_address" | "vendor_location" | "vendor_reach";

// From purchaseorders/completeness.go
export type PoIncompleteProblem = ProblemDetail & {
    issues: PoCompletenessIssue[];
};

// From purchaseorders/completeness.go
export type PoIssueKind = "client" | "po" | "shipping" | "vendor";

// From purchaseorders/dto.go
export type PoItemInput = {
    quotationItemId?: number;
    offeredItemId?: number;
    itemName: string;
    itemCode?: string;
    qty: string;
    unitId?: number;
    sellingPrice: string;
    costPrice?: string;
    isAvailable?: boolean;
    shipDestination?: string;
    vendorProductId?: number;
    vendorId?: number;
};

// From purchaseorders/dto.go
export type PoNotesInput = {
    notes: string;
};

// From purchaseorders/dto.go
export type PoSaved = {
    id: number;
    rowVersion: number;
};

// From purchaseorders/dto.go
export type PoStatusEvent = {
    id: number;
    fromStatus?: PoBackendStatus;
    toStatus: PoBackendStatus;
    note?: string;
    changedBy: number;
    changedAt: string;
};

// From purchaseorders/dto.go
export type PoStatusInput = {
    status: PoBackendStatus;
    note?: string;
};

// From purchaseorders/transitions.go
export type PoTransition = {
    to: PoBackendStatus;
    label: string;
    requiresNote: boolean;
};

// From purchaseorders/dto.go
export type PoUpdateItemsInput = {
    discountPct: string;
    notes?: string;
    shippingAddress?: string;
    shippingDays?: number;
    shippingCost?: string;
    items: PoItemInput[];
};

// From assetproxy/assetproxy.go
export type PresignDownload = {
    downloadUrl: string;
    expiresAt: number;
};

// From assetproxy/assetproxy.go
export type PresignFileDownload = PresignDownload & {
    fileName: string | null;
};

// From assetproxy/assetproxy.go
export type PresignUpload = {
    expiresAt: number;
    objectKey: string;
    uploadUrl: string;
};

// From httperr/httperr.go
export type ProblemDetail = {
    type: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
    fields?: Record<string, string>;
    code?: string;
};

// From purchaseorders/dto.go
export type PurchaseOrderItemRow = {
    id: number;
    poId: number;
    quotationItemId?: number;
    lineNumber: number;
    itemType: string;
    offeredItemId?: number;
    itemCode?: string;
    itemName: string;
    qty: string;
    unitId?: number;
    unitCode?: string;
    sellingPrice: string;
    costPrice?: string;
    subtotal: string;
    totalSelling: string;
    profitAmount?: string;
    shipDestination?: string;
    shippingDays?: number;
    isAvailable: boolean;
    vendorProductId?: number;
    vendorId?: number;
    vendorName?: string;
};

// From purchaseorders/dto.go
export type PurchaseOrderRow = {
    id: number;
    poNumber?: string;
    quotationId: number;
    quotationNo: string;
    companyClientId: number;
    companyName: string;
    poDate: string;
    status: PoBackendStatus;
    fileName?: string;
    fileSize?: number;
    uploadedAt?: string;
    notes?: string;
    objectKey?: string;
    discountPct: string;
    quotationTotal?: string;
    quotationSubtotal?: string;
    poSubtotal: string;
    poTotalProduk: string;
    poTotalProfit: string;
    poDppNilaiLain: string;
    poPpnAmount: string;
    poGrandTotal: string;
    poTotalDiscount: string;
    rowVersion: number;
    createdAt: string;
    updatedAt: string;
    deliveryNoteNumber?: string;
    deliveryNoteDate?: string;
    legacyDnNo?: string;
    invoiceNo?: string;
    linesLocked: boolean;
    allowedTransitions: PoTransition[];
};

// From quotations/dto.go
export type QuotationAddLinesInput = {
    items: QuotationItemInput[];
};

// From quotations/dto.go
export type QuotationContactInput = {
    contactId: number;
};

// From quotations/dto.go
export type QuotationCreateInput = {
    companyClientId: number;
    contactId?: number;
    clientRefNo?: string;
    vesselName?: string;
    paymentTerms?: string;
    validityDays?: number;
    discountPct: string;
    shippingAddress?: string;
    shippingDays?: number;
    shippingCost?: string;
    items: QuotationItemInput[];
    notes?: string;
    status?: QuotationStatus;
};

// From quotations/dto.go
export type QuotationCreated = {
    id: number;
};

// From quotations/dto.go
export type QuotationDetail = QuotationHeader & {
    items: QuotationItemRow[];
    history: QuotationStatusEvent[];
    allowedTransitions: QuotationTransition[];
    canRevise: boolean;
    locks: QuotationEditLock[];
};

// From quotations/dto.go
export type QuotationEditLock = {
    part: string;
    userId: number;
    userName: string;
    expiresAt: string;
};

// From quotations/dto.go
export type QuotationHeader = {
    id: number;
    quotationNo: string;
    legacyNo?: string;
    version: number;
    companyClientId: number;
    companyClientName: string;
    contactId?: number;
    contactName?: string;
    clientRefNo?: string;
    vesselName?: string;
    status: QuotationStatus;
    paymentTerms?: string;
    validityDays?: number;
    discountPct: string;
    totalProduk: string;
    total: string;
    totalDiscount: string;
    subtotal: string;
    dppNilaiLain: string;
    ppnAmount: string;
    grandTotal: string;
    notes?: string;
    rowVersion: number;
    createdAt: string;
    updatedAt: string;
};

// From quotations/dto.go
export type QuotationHeaderInput = {
    clientRefNo?: string;
    vesselName?: string;
    paymentTerms?: string;
    validityDays?: number;
    discountPct: string;
    shippingAddress?: string;
    shippingDays?: number;
    shippingCost?: string;
    notes?: string;
};

// From quotations/dto.go
export type QuotationItemInput = {
    requestedItemId?: number;
    requestedImpa?: string;
    requestedName: string;
    offeredItemId?: number;
    vendorProductId?: number;
    vendorId?: number;
    qty: string;
    unitId?: number;
    sellingPrice: string;
    costPrice?: string;
    updateVendorPrice?: boolean;
    shipDestination?: string;
    dueDate?: string;
    isAvailable?: boolean;
};

// From quotations/qir.go
export type QuotationItemRequestCreateInput = {
    lineNo: number;
    requestText: string;
    requestImpa?: string;
    requestedQty?: string;
    requestedUom?: string;
    matchedItemId?: number;
    matchStatus?: string;
    sourceType?: string;
    sourceRef?: string;
    notes?: string;
};

// From quotations/qir.go
export type QuotationItemRequestRow = {
    id: number;
    quotationId: number;
    lineNo: number;
    requestText: string;
    requestImpa?: string;
    requestedQty?: string;
    requestedUom?: string;
    matchedItemId?: number;
    matchStatus: string;
    sourceType: string;
    sourceRef?: string;
    notes?: string;
    reviewedBy?: number;
    reviewedAt?: string;
    rowVersion: number;
    createdBy: number;
    updatedBy?: number;
    createdAt: string;
    updatedAt: string;
};

// From quotations/qir.go
export type QuotationItemRequestUpdateInput = {
    lineNo: number;
    requestText: string;
    requestImpa?: string;
    requestedQty?: string;
    requestedUom?: string;
    matchedItemId?: number;
    matchStatus: string;
    sourceType: string;
    sourceRef?: string;
    notes?: string;
};

// From quotations/dto.go
export type QuotationItemRow = {
    id: number;
    quotationId: number;
    lineNumber: number;
    itemType: string;
    requestedItemId?: number;
    requestedImpa?: string;
    requestedName: string;
    offeredItemId?: number;
    offeredName?: string;
    offeredImpa?: string;
    vendorProductId?: number;
    vendorId?: number;
    vendorName?: string;
    qty: string;
    unitId?: number;
    sellingPrice: string;
    costPrice?: string;
    discountPct: string;
    totalSelling: string;
    discountAmount: string;
    subtotal: string;
    isAvailable: boolean;
    shipDestination?: string;
    shippingDays?: number;
};

// From quotations/dto.go
export type QuotationLineOfferInput = {
    isAvailable: boolean;
};

// From quotations/dto.go
export type QuotationLinesAdded = {
    ids: number[];
};

// From quotations/dto.go
export type QuotationListRow = {
    id: number;
    quotationNo: string;
    legacyNo?: string;
    version: number;
    companyClientId: number;
    companyName: string;
    status: QuotationStatus;
    grandTotal: string;
    subtotal: string;
    totalDiscount: string;
    totalHargaBeli: string;
    productCount: number;
    createdAt: string;
};

// From live/hub.go
export type QuotationLiveEvent = {
    quotationId: number;
    kind: string;
    part?: string;
    userId: number;
};

// From quotations/dto.go
export type QuotationLockGranted = {
    part: string;
    expiresAt: string;
};

// From quotations/dto.go
export type QuotationLockInput = {
    part: string;
};

// From quotations/dto.go
export type QuotationReviseInput = {
    note?: string;
};

// From quotations/dto.go
export type QuotationRevisionRow = {
    id: number;
    parentId?: number;
    quotationNo: string;
    version: number;
    status: QuotationStatus;
    grandTotal: string;
    totalProduk: string;
    createdAt: string;
    updatedAt: string;
};

// From quotations/rfq.go
export type QuotationRfqRows = {
    rows: MatchRowInput[];
};

// From quotations/dto.go
export type QuotationSaved = {
    id: number;
    rowVersion: number;
};

// From quotations/dto.go
export type QuotationSendInput = {
    note?: string;
};

// From quotations/status.go
export type QuotationStatus = "accepted" | "cancelled" | "draft" | "expired" | "rejected" | "revision" | "sent";

// From quotations/dto.go
export type QuotationStatusCount = {
    status: QuotationStatus;
    label: string;
    count: number;
};

// From quotations/dto.go
export type QuotationStatusEvent = {
    id: number;
    fromStatus?: QuotationStatus;
    toStatus: QuotationStatus;
    note?: string;
    changedBy: number | null;
    changedAt: string;
};

// From quotations/dto.go
export type QuotationStatusInput = {
    status: QuotationStatus;
    note?: string;
};

// From quotations/status.go
export type QuotationTransition = {
    to: QuotationStatus;
    label: string;
    requiresNote: boolean;
};

// From quotations/dto.go
export type QuotationUpdateInput = {
    clientRefNo?: string;
    vesselName?: string;
    paymentTerms?: string;
    validityDays?: number;
    discountPct: string;
    shippingAddress?: string;
    shippingDays?: number;
    shippingCost?: string;
    items: QuotationItemInput[];
    notes?: string;
};

// From users/dto.go
export type Role = "finance" | "operational" | "superadmin";

// From units/dto.go
export type UnitRow = {
    id: number;
    code: string;
    name?: string;
    coretaxCode?: string;
};

// From clients/dto.go
export type UpdateClientInput = {
    number?: string | null;
    name: string;
    npwp?: string | null;
    address?: string | null;
    email?: string | null;
    countryCode: string;
    tkuId?: string | null;
    isActive: boolean;
};

// From clients/dto.go
export type UpdateContactInput = {
    name: string;
    email?: string | null;
    phone?: string | null;
    title?: string | null;
    countryCode: string;
};

// From invoices/dto.go
export type UpdateInvoiceDatesInput = {
    invoiceDate?: string;
    dueDate?: string;
};

// From items/dto.go
export type UpdateItemInput = {
    name: string;
    impaCode?: string | null;
    defaultUnitId?: number | null;
    description?: string | null;
    isActive: boolean;
};

// From users/dto.go
export type UpdateUserInput = {
    email: string;
    name: string;
    role: Role;
    isActive: boolean;
};

// From vendors/dto.go
export type UpdateVendorInput = {
    name: string;
    location?: string | null;
    contactInfo?: VendorContactInfo | null;
    isActive: boolean;
};

// From users/dto.go
export type UserRow = {
    id: number;
    email: string;
    name: string;
    role: Role;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
};

// From vendors/dto.go
export type VendorContactInfo = {
    email?: string;
    phone?: string;
    sku?: string;
};

// From vendors/dto.go
export type VendorItemRow = {
    itemId: number;
    itemName: string;
    impaCode?: string;
    vendorSku?: string;
    costPrice?: string;
    lastQuotedAt?: string;
    productUrl?: string;
};

// From vendors/dto.go
export type VendorQuotationRow = {
    lineId: number;
    quotationId: number;
    quotationNo: string;
    quotationDate: string;
    status: string;
    clientId: number;
    clientName: string;
    contactName?: string;
    itemId?: number;
    itemName: string;
    impaCode?: string;
};

// From vendors/dto.go
export type VendorRow = {
    id: number;
    name: string;
    location?: string;
    contactInfo?: VendorContactInfo;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
    productCount: number;
    totalPurchase: string;
    logoObjectKey?: string;
};
