/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/items/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Multi-tier product search (legacy)
         * @description Trigram + IMPA prefix match scored across tiers.
         */
        get: {
            parameters: {
                query: {
                    q: string;
                    minScore?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matched items ranked by score. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResult"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/search-advanced": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Multi-tier product search with vendor offers and request history
         * @description Parallel merge of item-name trigram, vendor-offer match, and historical request-text match. Each hit is labelled with the strongest contributing tier and the full set of tiers that matched.
         */
        get: {
            parameters: {
                query: {
                    q: string;
                    minScore?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Merged tier-ranked hits. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdvancedSearchResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SearchResult: {
            /** Format: int64 */
            id: number;
            name: string;
            impaCode?: string | null;
            /** Format: int32 */
            defaultUnitId?: number | null;
            /** Format: float */
            score: number;
            /** @enum {string} */
            matchTier: "EXACT_IMPA" | "PREFIX_IMPA" | "TRIGRAM_NAME" | "VENDOR_OFFER" | "REQUEST_HISTORY";
        };
        /**
         * @description Canonical tier label exposed by /items/search-advanced.
         * @enum {string}
         */
        AdvancedSearchTier: "ITEM_AUTO" | "VENDOR_OFFER" | "ITEM_SUGGESTED" | "REQUEST_HISTORY" | "ITEM_FUZZY";
        AdvancedSearchHit: {
            /** Format: int64 */
            id: number;
            name: string;
            impaCode?: string | null;
            /** Format: int32 */
            defaultUnitId?: number | null;
            /** Format: float */
            score: number;
            tier: components["schemas"]["AdvancedSearchTier"];
            tiers: components["schemas"]["AdvancedSearchTier"][];
            /** Format: int64 */
            vendorId?: number | null;
            vendorName?: string | null;
            vendorSku?: string | null;
            requestText?: string | null;
        };
        AdvancedSearchResponse: {
            query: string;
            total: number;
            hits: components["schemas"]["AdvancedSearchHit"][];
            counts: {
                [key: string]: number;
            };
        };
        ApiError: {
            error: {
                message: string;
                code?: string;
                fields?: {
                    [key: string]: string;
                };
            };
        };
    };
    responses: {
        /** @description Request malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
